### ISSUE TITLE
Dealing with text while parsing text including "at"

### ISSUE THREAD

**Issue by afriese** [zachwill/moment#13]
Hi, 
if I try to parse the the following. I get an error that shouldnt appear.

moment.date("September 07, 2015 at", "MMMM DD, YYYY [at]")

ValueError: 'P' is a bad directive in format '%B %d, %Y [%Pt]'

Thanks for any help

**Comment by zachwill** [comment]
I would suggest stripping the `"at"` off:

    import moment

    test = "September 07, 2015 at"
    date = moment.date(test.strip(" at"), "%B %d, %Y")
    print date.format("YYYY-MM-DD")
