### ISSUE TITLE
type error when using add method

### ISSUE THREAD

**Issue by dsikes** [zachwill/moment#17]
When I use something like `moment.utcnow().add(years=3, months=2).format("YYYY-M-D h:m A")`
i get a type error that says `integer argument expected, got float`. How should I go about resolving this issue? I have tried a couple of things, but couldn't seem to get it to work as expected.

**Comment by dsikes** [comment]
nevermind. I am assuming it is a Python 3 issue, as I am running 3.5.1. Any word on when Moment will be fully supported in Python 3?

**Comment by zachwill** [comment]
Just pushed a new release that should solve this problem.
