### ISSUE TITLE
Travis integration is broken

### ISSUE THREAD

**Issue by wojcikstefan** [zachwill/moment#19]
Hi @zachwill ! I noticed that the build badge in the readme doesn't render properly:

<img width="175" alt="screen shot 2016-10-24 at 12 07 23 pm" src="https://cloud.githubusercontent.com/assets/1718372/19653447/94fa6f06-99e2-11e6-9d44-fc460f5377c1.png">

And when you click on it, Travis says "The repository at zachwill/moment was not found."

You should be able to re-add the repo to Travis on https://travis-ci.org/profile/.

**Comment by pratikgadiya12** [comment]
@zachwill : The owner of the repository can only create/add repository on travis-ci.
I have already made the changes in READ.md for travis integration and will sent the PR for the same.
