### ISSUE TITLE
Parsing a year creates a date in the 1st of July

### ISSUE THREAD

**Issue by msamoylov** [zachwill/moment#25]
Is it a bug or undocumented feature? Not sure if I understand it. Thanks in advance.

```
In [1]: import moment

In [2]: moment.date('2000').date
Out[2]: datetime.datetime(2000, 7, 1, 0, 0)
```

**Comment by zachwill** [comment]
Hmmm, good catch. Looks like it's part of [`dateparser`'s](https://github.com/scrapinghub/dateparser) default settings. Don't see a flag to change it to January.

**Comment by zachwill** [comment]
Until there's an update in `dateparser`, I'm not sure how to change this behavior. Sorry about that.
