### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by maludwig** [zachwill/moment#27]
Hey,

I'd very much like this project to be fleshed out more to be on par with moment.js, but I don't want to make Pull Requests and stuff on a project that isn't being maintained.

I'm happy making PRs or, if you don't want to handle this anymore, I'm also happy with taking over the package.

**Comment by zachwill** [comment]
Hey @maludwig,

More of a personal project than one I'd like to add a ton of features to. You might be interested in helping shape the `arrow` package: https://github.com/crsmithdev/arrow/

Hope that helps,

Zach
