### ISSUE TITLE
Is this library dead?

### ISSUE THREAD

**Issue by cyberfox1** [zachwill/moment#37]
Seems pretty broken...no updates for a year.

**Comment by AdrienHorgnies** [comment]
It looks like so, too bad, I really like the moment library in other languages.

**Comment by erlei22** [comment]
pity

**Comment by ei-grad** [comment]
Are there any maintained forks?

**Comment by AdrienHorgnies** [comment]
@ei-grad Not what you're asking but everybody pointed me to [pendulum](https://pypi.org/project/pendulum/).

**Comment by zachwill** [comment]
Pendulum and Arrow are better options 👍
