### ISSUE TITLE
 Calculate the datetime before 12 months

### ISSUE THREAD

**Issue by fzitou** [zachwill/moment#40]
this is what I am using now:
 moment.now().add(years=-2, months=-12, days=-3).format('YYYY-M-D')

The reason is that the parameter is not considered as a negative number in the moment.date.update_month method.

**Comment by zachwill** [comment]
Hey @fzitou,

Think you're looking for the `sub` or `subtract` method:

```python
import moment

months = (2 * 12) + 12  # 36 months
moment.now().sub(months=months, days=3).format("YYYY-M-D")
```
