### ISSUE TITLE
 Cross year display error

### ISSUE THREAD

**Issue by Childdreams** [zachwill/moment#42]
month = moment.now().sub(month=20).format("%Y-MM")
print (month)

-------------------
month  : 2020-03 
now : 2020-11-19 

Correct results 2019-03

**Comment by Childdreams** [comment]
my python version : 3.7 
date.py line 30  
should be` year = date.year + int(month // 12) `
not `year = date.year + int(month / 12)`

**Comment by Childdreams** [comment]
my python version : 3.7
date.py line 30
should be`year = date.year + int(month // 12)` 
not `year = date.year + int(month / 12)`
because  line 25 `month = date.month - 1 - number`

**Comment by zachwill** [comment]
Sorry about this bug, @Childdreams. Version `0.12` should fix it for you 👍
