### ISSUE TITLE
how can i use moment diff get a seconds measurement result

### ISSUE THREAD

**Issue by Jakin-Liu** [zachwill/moment#44]
@classmethod
    def diff(cls, start_time: Moment, end_time: Moment, diff_type=None):
        if not diff_type:
            diff_type = 'seconds'
        start = cls.get_current_moment(start_time)
        end = cls.get_current_moment(end_time)
        return end.diff(start)

**Comment by zachwill** [comment]
```python
day_1 = moment.date("2021-01-01")
day_2 = moment.date("2021-02-01")

diff_seconds = abs((day_1 - day_2).total_seconds())
print(diff_seconds)
```
