### ISSUE TITLE
支持中文显示时间吗？

### ISSUE THREAD

**Issue by wuqiang-001** [zachwill/moment#47]
支持中文显示时间吗？
刚刚..    1分钟前   2分钟前  半小时前

**Comment by zachwill** [comment]
Hey, I don't believe it can handle Chinese display time like: "1 minute ago", "2 minutes ago", etc. Sorry!

Using Google translate:

我不相信它可以像 1 分钟前、2 分钟前那样翻译中国时间——对不起。
