### ISSUE TITLE
Incorrect Results for Parssing Data Time

### ISSUE THREAD

**Issue by OrianeK** [zachwill/moment#48]
Hi,
I am a high school student just starting to learn about testing techniques. I found a bug in the latest version (0.12.1) of moment while doing some fuzzing using the fuzzing tool Atheris. The reproducing process is shown below:

```
import moment
moment.date('2001W5')
```

Results
`<Moment(1984-01-03T17:32:28)>`

My Environment
```
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux 
moment in /home/clou5/.local/lib/python3.8/site-packages (0.12.1)
```

I am still not very sure about the bug so I would very much appreciate any kind of feedback regarding it.
Thanks.

**Comment by zachwill** [comment]
Hey @OrianeK,

Thanks for the bug report! Under the hood, `moment` uses `dateparser`: https://github.com/scrapinghub/dateparser

Looks like the bug actually lies in their side of things:

```python
import dateparser

dateparser.parse("2001W5")
```

Hope that helps!
