### ISSUE TITLE
epoch does not return the same Unix Timestamp

### ISSUE THREAD

**Issue by byukan** [zachwill/moment#49]
moment.unix(t).epoch() does not equal t.   

t = 1653430533339. # GMT: Tuesday, May 24, 2022 10:15:33.339 PM
moment.unix(t).epoch(). # 1653405333   ->   GMT: Tuesday, May 24, 2022 3:15:33 PM

<img width="204" alt="image" src="https://user-images.githubusercontent.com/12012907/171748649-6f6c9f5e-d763-4271-a39a-54228a0be9cb.png">

**Comment by zachwill** [comment]
Hey @byukan,

Here's code that gets a relatively close `epoch` (1653430533000):

```python
t = 1653430533339
moment.unix(t, utc=True).epoch(milliseconds=True)
```
