### ISSUE TITLE
Allow specifying the format/locale for month and day display

### ISSUE THREAD

**Issue by Seluj78** [zachwill/moment#50]
Hello,

I need to parse dates easily with different formats and `moment` is amazing for this, and I thank you very much for your work!

As you may or may not know, the US always does stuff differently than the rest of the world and, for example, display their dates month first (which IMO makes no sense) but makes it a hassle for parsing.

See my example here:

```python
>>> moment.date("11/05/2022").strftime("Month: %m, Day: %d, Year: %Y")
'Month: 11, Day: 05, Year: 2022'
```

Whereas I would've expected it to output the 11th of May... I tried using the `.locale()` method but it didn't fix it. Any idea ?

**Comment by zachwill** [comment]
Hey @Seluj78,

Think there might be two ways to tackle it (under the hood `moment` uses `dateparser`):

```python
import dateparser
import moment

# Know the format ahead of time?
moment.date("11/05/2021", "%d/%m/%Y")

# Know the language/locale ahead of time and want a datetime?
date = dateparser.parse("11/05/2021", languages=["es"])
moment.date(date)
```

`dateparser` is really nice when you're scraping a bunch of dates from a certain language. (I chose Spanish in the example above.)
